language: csharp
solution: CSharpSeleniumFramework.sln
install:
  - nuget restore CSharpSeleniumFramework.sln
  - nuget install NUnit.ConsoleRunner -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug CSharpSeleniumFramework.sln
  - mono ./testrunner/nunit.consolerunner.3.8.0/tools/nunit3-console.exe ./CSharpSeleniumFramework/bin/Debug/CSharpSeleniumFramework.dll